# Generated by Django 4.1.7 on 2023-03-11 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_date_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='auctions.asset'),
        ),
    ]
