# Generated by Django 4.1.7 on 2023-03-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bid_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatchlist',
            field=models.ManyToManyField(related_name='whatchlist', to='auctions.asset'),
        ),
    ]
