# Generated by Django 4.1.7 on 2023-03-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_user_whatchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='whatchlist',
            field=models.ManyToManyField(blank=True, related_name='whatchlist', to='auctions.asset'),
        ),
    ]
