# Generated by Django 4.1.7 on 2023-03-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_user_whatchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='whatchlist',
        ),
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='auctions.asset'),
        ),
    ]
