# Generated by Django 4.1.7 on 2023-03-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_user_whatchlist_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
