# Generated by Django 4.1.7 on 2023-03-16 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_asset_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auctions.asset'),
        ),
    ]
